kss/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('booking.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True,)
    first_name = models.CharField(max_length=100, null=False, blank=False)
    last_name = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    phone_num = models.CharField(max_length=20, null=False, blank=False)
    date_of_birth = models.DateField(null=False, blank=False)
    height = models.DecimalField(
        max_digits=3, decimal_places=2, null=False, blank=False)
    weight = models.DecimalField(
        max_digits=4, decimal_places=1, null=False, blank=False)

    def __str__(self):
        """
        Defines the name for an instance object of the
        Customer model overwriting the django default method.
        """
        return self.user.username


class Booking(models.Model):
    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='bookings')
    ability_level = models.CharField(max_length=50, null=False, blank=False)
    lesson_date = models.DateField(null=False, blank=False)
    lesson_time = models.TimeField(null=False, blank=False)
    customer_requests = models.TextField(null=True, blank=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        """
        Defines the name for an instance object of the
        Booking model overwriting the django default method.
        """
        return str(self.lesson_date)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
        content="Kerry Surf School for surfing lessons and surfing equipment hire in Kerry, Ireland">
    <meta name="keywords"
        content="kerry surf school, surfing lessons, beginner surfing lessons, adult lessons, kids lessons, surfing equipment hire, rent a surfboard, hire a wetsuit">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel='shortcut icon' type='image/x-icon' href="{% static 'favicon/favicon.ico' %}">
    <title>Kerry Surf School</title>
</head>

<body class="light-brown-bg-color">
    <header>
        <nav class="navbar fixed-top navbar-expand-sm bg-body-tertiary py-0">
            <div class="container-fluid light-blue-bg-color">
                <a class="navbar-brand me-5-md text-styling" href="{% url 'index' %}">KSurf</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item mx-md-3 mx-lg-5">
                            <a {% if request.path == '/' %} class="nav-link active text-styling" {% else %}
                                class="nav-link text-styling" {% endif %} aria-current="page"
                                href="{% url 'index' %}">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item mx-md-3 mx-lg-5">
                            <a {% if request.path == '/customer/' %} class="nav-link active text-styling" {% else %}
                                class="nav-link text-styling" {% endif %} href="{% url 'customer' %}">My Account</a>
                        </li>
                        <li class="nav-item mx-md-3 mx-lg-5">
                            <a {% if request.path == '/accounts/logout/' %} class="nav-link active text-styling"
                                {% else %} class="nav-link text-styling" {% endif %}
                                href="{% url 'account_logout' %}">Log Out</a>
                        </li>
                        {% else %}
                        <li class="nav-item mx-md-3 mx-lg-5">
                            <a {% if request.path == '/accounts/signup/' %} class="nav-link active text-styling"
                                {% else %} class="nav-link text-styling" {% endif %}
                                href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item mx-md-3 mx-lg-5">
                            <a {% if request.path == '/accounts/login/' %} class="nav-link active text-styling"
                                {% else %} class="nav-link text-styling" {% endif %}
                                href="{% url 'account_login' %}">Log In</a>
                        </li>
                        {% endif %}
                        <li class="nav-item mx-md-3 mx-lg-5">
                            <a class="nav-link text-styling admin-link-col" href="{% url 'admin:login' %}">Admin Only</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <section class="text-center title-styles d-flex flex-column mobile-title-position">
            <h1 class="pt-5 ps-lg-3">Kerry Surf School</h1>
        </section>
        <div class="d-flex flex-column flex-md-row justify-content-around light-blue-bg-color bottom-margin-10">
            <span>Telephone: 555 1234567</span>
            <span>Email: ksurf@email.ie</span>
            <span>Office Hours: 10am - 5pm Monday to Saturday</span>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% block content %}

    {% endblock content %}
    <footer class="light-blue-bg-color">
        <ul>
            <li><a href="https://www.facebook.com/" target="_blank" rel="noopener"
                    aria-label="Visit us on Facebook (opens in a new tab)"><i
                        class="fa-brands fa-square-facebook"></i></a>
            </li>
            <li><a href="https://www.instagram.com/" target="_blank" rel="noopener"
                    aria-label="Visit us on Instagram (opens in a new tab)"><i class="fa-brands fa-instagram"></i></a>
            </li>
            <li><a href="https://twitter.com/" target="_blank" rel="noopener"
                    aria-label="Visit us on Twitter (opens in a new tab)"><i class="fa-brands fa-twitter"></i></a>
            </li>
            <li><a href="https://www.youtube.com/" target="_blank" rel="noopener"
                    aria-label="Visit us on youtube (opens in a new tab)"><i class="fa-brands fa-youtube"></i></a>
            </li>
        </ul>
    </footer>

    <!-- Bootstrap Script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
    </script>
    <!-- jquery Script -->
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <!-- Font Awesome Script -->
    <script src="https://kit.fontawesome.com/4e8d2c2bb0.js" crossorigin="anonymous"></script>
    <!-- js file Script -->
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/customer.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<main>
    <h2 class="ps-3">Welcome {{ user.username }}!</h2>
    <div class="container top-margin-30">
        <div class="row">
            <div class="col-12 col-sm">
                <h3>Your Details:</h3>
            </div>
            <div class="col">
                <p><strong>Name:</strong> {{ user.customer.first_name }} {{ user.customer.last_name}}</p>
                <p><strong>Email:</strong> {{ user.customer.email}}</p>
                <p><strong>Telephone Number:</strong> {{ user.customer.phone_num}}</p>
                <p><strong>Date of Birth:</strong> {{ user.customer.date_of_birth }}</p>
                <p><strong>Height:</strong> {{user.customer.height }}m</p>
                <p><strong>Weight:</strong> {{ user.customer.weight }}kg</p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-10 offset-1 my-3">
                <p>From here you can make as many bookings for yourself as needed!</p>
                <p>To edit or cancel bookings select the option to View you Bookings! and
                    then follow the steps from there.
                </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm d-flex justify-content-center top-margin-30">
                <a href="{% url 'make_booking' %}" class="btn light-blue-btn-bg-color text-styling">Make a
                    booking!</a>
            </div>
            <div class="col-12 col-sm d-flex justify-content-center top-margin-30">
                <a href="{% url 'view_bookings' %}" class="btn light-blue-btn-bg-color text-styling">View your
                    bookings!</a>
            </div>
            <div class="col-12 col-sm d-flex justify-content-center top-margin-30">
                <a href="{% url 'edit_customer' %}" class="btn light-blue-btn-bg-color text-styling">Edit your
                    Details!</a>
            </div>
            <div class="col d-flex justify-content-center top-margin-30">
                <button type="button" class="btn btn-danger text-styling mt-2" data-bs-toggle="modal"
                    data-bs-target="#confirmDeleteUserModal">
                    Delete Account!!
                </button>
            </div>
        </div>
    </div>
</main>
<!-- Modal -->
<div class="modal fade" id="confirmDeleteUserModal" tabindex="-1" aria-labelledby="confirmDeleteUser"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title fs-5" id="confirmDeleteUser">Are you sure you want to delete this account?</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Proceeding with the deletion of this account will permanently delete the
                account from our database and will also immediately delete
                any current bookings associated with the account.
                Click Confirm Delete Account!! if you wish to proceed.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Go back!</button>
                <a href="{% url 'delete_user' %}" class="btn btn-danger text-styling">Confirm Delete Account!!</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/customer_first_login.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<main>
    <h2 class="ps-3">Welcome, {{ user.username }}!</h2>
    <p class="ps-3">Please complete the customer profile below:</p>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2 d-flex justify-content-center">
                <form method="POST" action="/customer/firstlogin/">
                    {% csrf_token %}
                    <p>
                        {{ form.non_field_errors }}
                    </p>
                    <p>
                        {{ form.first_name.label_tag }}
                    </p>
                    <p>
                        {{ form.first_name.errors }}
                        {{ form.first_name }}
                    </p>
                    <p>
                        {{ form.last_name.label_tag }}
                    </p>
                    <p>
                        {{ form.last_name.errors }}
                        {{ form.last_name }}
                    </p>
                    <p>
                        {{ form.email.label_tag }}
                    </p>
                    <p>
                        {{ form.email.errors }}
                        {{ form.email }}
                    </p>
                    <p>
                        <label for="id_phone_num">Telephone Number:</label>
                    </p>
                    <p>
                        {{ form.phone_num.errors }}
                        <input type="tel" pattern="[0-9, '', +]+" name="phone_num" {% if form.phone_num.value == None %}
                            placeholder="000" {% else %} value="{{ form.phone_num.value }}" {% endif %} maxlength="20"
                            required id="id_phone_num">
                    </p>
                    <p>
                        <label for="id_date_of_birth">Date of birth:</label>
                    </p>
                    <p>
                        {{ form.date_of_birth.errors }}
                        <input type="date" name="date_of_birth" value="{{ form.date_of_birth.value }}" required
                            id="id_date_of_birth">
                    </p>
                    <p>
                        {{ form.height.label_tag }} (In metres. Max 2 decimal places)
                    </p>
                    <p>
                        {{ form.height.errors }}
                        <input type="number" name="height" value="{{ form.height.value }}" step="0.01" required
                            id="id_height" min="0" max="3" placeholder="0.00"> m
                    </p>
                    <p>
                        {{ form.weight.label_tag }} (In kg. Max 1 decimal place)
                    </p>
                    <p>
                        {{ form.weight.errors }}
                        <input type="number" name="weight" value="{{ form.weight.value }}" step="0.1" required
                            id="id_weight" min="0" max="999" placeholder="000.0"> kg
                    </p>
                    <button class="btn light-blue-btn-bg-color my-2" type="submit">Submit Details</button>
                </form>
            </div>
        </div>
    </div>

    <p class="ps-3 m-3">The details you provide are necessary to process your booking
        and will not be used for any other purpose. Weight, height, and date of birth
        are used to ensure students are placed in the appropriate class with the
        appropriate surfing equipment. We will use your email to send confirmation
        of any bookings and to communicate with you regarding your booking.
        We will only use your telephone number to contact you if needed at
        short notice regarding your booking. The details you provide will only be
        used for purposes directly related to your booking. Thank you!
    </p>
</main>
<script src="{% static 'js/dateOfBirth.js' %}" defer></script>
{% endblock content %}

templates/edit_booking.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<main>
    <h2 class="ps-3">You can edit the selected booking here {{ user.username }}!</h2>
    <p class="ps-3">(Bookings for today cannot be made online. Please phone to check today's availability)</p>
    <p class="ps-3">Please edit the appropriate fields and submit changes once you are ready to do so:</p>
    <p class="ps-3">(Please include any special requirements or requests in the Customer requests box and we will do or
        best to accomodate you!) </p>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2 d-flex justify-content-center">
                <form method="POST">
                    {% csrf_token %}
                    <p>
                        <label for="id_ability_level">Ability level:</label>
                    </p>
                    <p>
                        <select name="ability_level" id="id_ability_level" required>
                            <option value="">Please choose one!</option>
                            <option value="Beginner">Beginner</option>
                            <option value="Intermediate">Intermediate</option>
                        </select>
                    </p>
                    <p>
                        <label for="id_lesson_date">Lesson date:</label>
                    </p>
                    <p>
                        <input type="date" name="lesson_date" required id="id_lesson_date">
                    </p>
                    <p>
                        <label for="id_lesson_time">Lesson Time:</label>
                    </p>
                    <p>
                        <select name="lesson_time" id="id_lesson_time" required>
                            <option value="">Please choose one!</option>
                            <option value="9:00">9:00am</option>
                            <option value="11:00">11:00am</option>
                            <option value="13:30">1:30pm</option>
                            <option value="15:30">3:30pm</option>
                        </select>
                    </p>
                    <p>
                        {{ form.customer_requests.label_tag }}
                    </p>
                    <p>
                        {{ form.customer_requests }}
                    </p>
                    <button class="btn light-blue-btn-bg-color my-2" type="submit">Update Booking!</button>
                    <a href="{% url 'view_bookings' %}" class="btn light-blue-btn-bg-color text-styling my-2 ms-3">Go
                        Back!</a>
                </form>
            </div>
        </div>
    </div>
    <p class="ps-3">All of the above details are required to confirm your booking.
        The information provided will be used for no other purpose other than
        to administer your booking and provide an appropriate lesson.
    </p>
</main>

<script src="{% static 'js/editBooking.js' %}" defer data-lesson-date="{{ booking.lesson_date }}"
    data-ability-level="{{ booking.ability_level }}" data-lesson-time="{{ booking.lesson_time }}"></script>

<script src="{% static 'js/date.js' %}" defer></script>
{% endblock content %}

templates/edit_profile.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<main>
    <h2 class="ps-3">You can edit your customer profile here {{ user.username }}!</h2>
    <p class="ps-3">Please edit the appropriate fields and submit changes once you are ready to do so:</p>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2 d-flex justify-content-center">
                <form method="POST">
                    {% csrf_token %}
                    <p>
                        {{ form.non_field_errors }}
                    </p>
                    <p>
                        {{ form.first_name.label_tag }}
                    </p>
                    <p>
                        {{ form.first_name.errors }}
                        {{ form.first_name }}
                    </p>
                    <p>
                        {{ form.last_name.label_tag }}
                    </p>
                    <p>
                        {{ form.last_name.errors }}
                        {{ form.last_name }}
                    </p>
                    <p>
                        {{ form.email.label_tag }}
                    </p>
                    <p>
                        {{ form.email.errors }}
                        {{ form.email }}
                    </p>
                    <p>
                        <label for="id_phone_num">Telephone Number:</label>
                    </p>
                    <p>
                        {{ form.phone_num.errors }}
                        <input type="tel" pattern="[0-9, '', +]+" name="phone_num" value="{{ form.phone_num.value }}"
                            maxlength="20" required id="id_phone_num">
                    </p>
                    <p>
                        <label for="id_date_of_birth">Date of birth:</label>
                    </p>
                    <p>
                        {{ form.date_of_birth.errors }}
                        <input type="date" name="date_of_birth" required id="id_date_of_birth">
                    </p>
                    <p>
                        {{ form.height.label_tag }} (In metres. Max 2 decimal places)
                    </p>
                    <p>
                        {{ form.height.errors }}
                        <input type="number" name="height" value="{{ form.height.value }}" step="0.01" required
                            id="id_height" min="0" max="3" placeholder="0.00"> m
                    </p>
                    <p>
                        {{ form.weight.label_tag }} (In kg. Max 1 decimal place)
                    </p>
                    <p>
                        {{ form.weight.errors }}
                        <input type="number" name="weight" value="{{ form.weight.value }}" step="0.1" required
                            id="id_weight" min="0" max="999" placeholder="000.0"> kg
                    </p>
                    <button class="btn light-blue-btn-bg-color my-2" type="submit">Update Profile!</button>
                    <a href="{% url 'customer' %}" class="btn light-blue-btn-bg-color text-styling my-2 ms-3">Go
                        Back!</a>
                </form>
            </div>
        </div>
    </div>
    <p class="ps-3">All of the above details are required to confirm your booking.
        The information provided will be used for no other purpose other than
        to administer your booking and provide an appropriate lesson.
    </p>
</main>

<script src="{% static 'js/editProfile.js' %}" defer data-dob="{{ form.date_of_birth.value }}"></script>
<script src="{% static 'js/dateOfBirth.js' %}" defer></script>

{% endblock content %}

templates/make_booking.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<main>
    <h2 class="ps-3">You can make a booking here {{ user.username }}!</h2>
    <p class="ps-3">(Bookings for today cannot be made online. Please phone to check today's availability)</p>
    <p class="ps-3">Please complete the form in full:</p>
    <p class="ps-3">(Please include any special requirements or requests in the Customer requests box and we will do or
        best to accomodate you!) </p>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2 d-flex justify-content-center">
                <form method="POST" action="/book/">
                    {% csrf_token %}
                    <p>
                        <label for="id_ability_level">Ability level:</label>
                    </p>
                    <p>
                        <select name="ability_level" id="id_ability_level" required>
                            <option value="">Please choose one!</option>
                            <option value="Beginner">Beginner</option>
                            <option value="Intermediate">Intermediate</option>
                        </select>
                    </p>
                    <p>
                        <label for="id_lesson_date">Lesson date:</label>
                    </p>
                    <p>
                        <input type="date" name="lesson_date" required id="id_lesson_date">
                    </p>
                    <p>
                        <label for="id_lesson_time">Lesson Time:</label>
                    </p>
                    <p>
                        <select name="lesson_time" id="id_lesson_time" required>
                            <option value="">Please choose one!</option>
                            <option value="9:00">9:00am</option>
                            <option value="11:00">11:00am</option>
                            <option value="13:30">1:30pm</option>
                            <option value="15:30">3:30pm</option>
                        </select>
                    </p>
                    <p>
                        {{ form.customer_requests.label_tag }}
                    </p>
                    <p>
                        {{ form.customer_requests }}
                    </p>
                    <button class="btn light-blue-btn-bg-color my-2" type="submit">Make Booking!</button>
                    <a href="{% url 'customer' %}" class="btn light-blue-btn-bg-color text-styling my-2 ms-3">Go
                        Back!</a>
                </form>
            </div>
        </div>
    </div>
    <p class="ps-3 m-3">All of the above details are required to make your booking.
        The information provided will be used for no other purpose other than
        to adminsiter your booking and provide an appropriate lesson.
    </p>
</main>
<script src="{% static 'js/date.js' %}" defer></script>
{% endblock content %}

templates/signup_login_links.html
{% extends "base.html" %}

{% block content %}

<main>
    <div class="container-fluid text-center">
        <div class="row">
            <div class="col-12 col-lg-6 top-margin-30">
                <div class="book-card m-auto d-flex flex-column justify-content-around">
                    <h2 class="text-height-action text-styling">New to Kerry Surf School?</h2>
                    <a href="{% url 'account_signup' %}"
                        class="btn light-blue-btn-bg-color text-height-action m-auto text-styling">Sign Up!</a>
                    <p class="text-height-action text-styling">Please create an Account!</p>
                </div>
            </div>
            <div class="col-12 col-lg-6 top-margin-30">
                <div class="book-card m-auto d-flex flex-column justify-content-around">
                    <h2 class="text-height-action text-styling">Already have an Account?</h2>
                    <a href="{% url 'account_login' %}"
                        class="btn light-blue-btn-bg-color text-height-action m-auto text-styling">Log In!</a>
                    <p class="text-height-action text-styling">Please log in to continue!</p>
                </div>
            </div>
        </div>
    </div>
    <div class="ps-3">
        <h3 class="top-margin-30">Why Do I Need an Account?</h3>
        <p>Please note that no payment details are required to create this account.
            All payments are made on the day prior to the lesson.
            We do need to record some basic information to save your booking including contact details.
            We will only contact you regarding your booking if it becomes necessary and your
            information will not be used for any other other purpose.
            An account allows you to review the information you provided to us at any time at your convenience.
        </p>
    </div>
</main>
{% endblock %}

templates/view_bookings.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main>
    <h2 class="ps-3">All bookings made by {{ user.username }}! ({{ user.customer.first_name }} {{ user.customer.last_name }})</h2>
    <a href="{% url 'customer' %}" class="btn light-blue-btn-bg-color text-styling m-3">Back to Account Summary!</a>
    <div id="all-bookings" class="d-flex justify-content-around flex-wrap">
        {% for booking in bookings %}
        <div class='d-inline-block border border-info p-2 m-2 min-width-220'>
            <p class="bottom-margin-2"><strong>Ability Level:</strong></p>
            <p>{{ booking.ability_level }}</p>
            <p class="bottom-margin-2"><strong>Lesson Booked for:</strong></p>
            <p>{{ booking.lesson_date }} at {{ booking.lesson_time}}</p>
            <p class="bottom-margin-2"><strong>Your Requests:</strong></p>
            <p>{{ booking.customer_requests }}</p>
            <a href="/edit/{{ booking.id }}" class="btn light-blue-btn-bg-color text-styling mt-2">Edit Booking</a>
            <button type="button" class="btn btn-danger text-styling mt-2" data-bs-toggle="modal"
                data-bs-target="#confirmDeleteModal" data-delete-href="/delete/{{ booking.id }}">
                Cancel Booking
            </button>
        </div>
        {% endfor %}
    </div>
</main>
<!-- Modal -->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDelete" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title fs-5" id="confirmDelete">Are you sure you want to delete this booking?</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Proceeding with the cancellation of this booking will permanently delete the
                booking from our bookings list. Click confirm cancellation if you wish to proceed.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Go back!</button>
                <a id="confirm" class="btn btn-danger text-styling">Confirm Cancellation</a>
            </div>
        </div>
    </div>
</div>
<!-- js file Script -->
<script src="{% static 'js/delete.js' %}" defer></script>
{% endblock %}